name: singular_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  graphql_flutter: ^5.0.0
  intl: ^0.17.0
  freezed: ^1.0.0
  json_annotation: ^4.4.0
  animations: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.2
  json_serializable: ^6.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
